### ISSUE TITLE
API Msg sync changes need addressing

### ISSUE THREAD

**Issue by rethink-rlinsalata** [RethinkRobotics/baxter_common#36]
Further attention needs to be paid to the API message changes introduced, specifically in PR / Issue #31 

Opening this issue so that we can merge the sync PR to continue development, but so before release we make sure that we address all changes necessary, address backwards compatibility / proper deprecation, and any additional changes that should go in / not go in before our 0.8 release

For example: Dan's comment on the original PR:
https://github.com/RethinkRobotics/baxter_common/pull/31#commitcomment-5272700

**Comment by rethink-imcmahon** [comment]
I think this is safe to close now, as it seems rather outdated.
