### ISSUE TITLE
Evaluate Hardware Interface and Zero Gravity URDF tags in Baxter

### ISSUE THREAD

**Issue by rethink-imcmahon** [RethinkRobotics/baxter_common#61]
@rethink-hmalaichamee updated Baxter's URDF to use extra tags to work with baxter_simulator in Indigo/Gazebo 2.0 via PR #57 . He said the following:

- I had added the <gravity> tag under each link in the URDF to turn off the gravity for those links. Unfortunately, it showed no effects and I had to do the above specified method to disable gravity. Need to remove those tags and test if it works.

- In the URDF <hardwareInterface> tag was added to the joints as required (in Indigo) in addition to those in the actuators. Rob asked me to remove them from the actuators since they are no more mandatory. However, this had an error that caused the simulator to fail when there was no such tag for the actuator. This needs to be removed and tested.

I am merging these tags since I've tested the URDF with them and they work, but I would like to know more about them & make sure they are necessary.

**Comment by rethink-imcmahon** [comment]
This PR is more or less resolved by the commits in #71

**Comment by davetcoleman** [comment]
Out of curiosity why was gravity turned off in the URDF? Seems like a nice feature to have in a physics simulator...
