### ISSUE TITLE
baxter.urdf.xacro missing?

### ISSUE THREAD

**Issue by alecive** [RethinkRobotics/baxter_common#82]
Hello,

I was looking to retrieve an URDF model for the Baxter robot, and I found this [`baxter.urdf` file](https://github.com/RethinkRobotics/baxter_common/blob/master/baxter_description/urdf/baxter.urdf).

Problem is that the file itself says it is deprecated, and it has been replaced by `baxter.urdf.xacro` (see [line 6 of the file](https://github.com/RethinkRobotics/baxter_common/blob/master/baxter_description/urdf/baxter.urdf#L6)), but said file is missing.

**Comment by IanTheEngineer** [comment]
Is this the file you're referring to? [/baxter_description/urdf/baxter.urdf.xacro](https://github.com/RethinkRobotics/baxter_common/blob/master/baxter_description/urdf/baxter.urdf.xacro)

**Comment by alecive** [comment]
Mm interesting. This made me realize that the code on our Baxter is still at version 1.1.1 (the xacro is available since version 1.2.0, but the deprecation occurred before apparently).

Thanks for the tip!
