### ISSUE TITLE
Remove baxter.urdf

### ISSUE THREAD

**Issue by davetcoleman** [RethinkRobotics/baxter_common#87]
This file is an artifact before ``baxter.urdf.xacro`` was created in a newer Baxter API version. There is currently differences between the two files - .urdf is not simply the generated output of the .xacro file. For example, .urdf has gravity tags and .xacro does not.

I think the .urdf file should be removed to avoid confusion

**Comment by IanTheEngineer** [comment]
I'll take that recommendation into consideration. I do get asked fairly often for the URDF, so it is handy to be able to point people at a single file rather than a requiring them to `xacro` it themselves. I do agree, however, that the `baxter.urdf` should at least be up-to-date

**Comment by davetcoleman** [comment]
I'd suggest instead you provide a bash script in the repo that will easily generate the URDF on demand - this is what I always do in my repos. Then add the *.urdf to the .gitignore file.

**Comment by IanTheEngineer** [comment]
Resolved by #86
