### ISSUE TITLE
Baxter head collision mesh

### ISSUE THREAD

**Issue by davetcoleman** [RethinkRobotics/baxter_common#9]
The Baxter is unable to reach its max joint limit for joint S1 because of collisions with the two head collision meshes:

- collision_head_link_1
- collision_head_link_2

Can these be shrunk further or are they important? It seems like if we know the angular location of the screen we don't need to have such a course-grained collision model. This is causing inaccuracies in Gazebo.

![baxterheadcollision](https://f.cloud.github.com/assets/561060/898405/204ea0b0-fb10-11e2-98b2-a4b1f8a1abf1.png)

**Comment by rethink-imcmahon** [comment]
While I believe the request here is still valid, I don't think the priority is high since Baxter currently functions well in Gazebo.
